//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica
{
    using System;
    using System.Collections.Generic;

    public partial class Detalle_Factura
    {
        public int IDDetalleFactura { get; set; }
        public int Cantidad { get; set; }

        public decimal Total
        {
            get
            {
                return Producto != null ? (Producto.PrecioVenta * Cantidad) : 0;
            }
        }
        public Factura Factura { get; set; }
        public Producto Producto { get; set; }
    }
}
