//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica
{
    using System;
    using System.Collections.Generic;

    public partial class Factura
    {
        public Factura()
        {
            //this.Detalle_Factura = new HashSet<Detalle_Factura>();
        }

        public int IDFactura { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<decimal> Monto { get; set; }

        public Cliente Cliente { get; set; }
        public ICollection<Detalle_Factura> Detalle_Factura { get; set; }
        public Usuario Usuario { get; set; }
    }
}
